# Generated by Django 2.2 on 2020-04-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=150)),
                ('course', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
    ]
